### PR TITLE
bigquery schema files and load scripts

### PR DESCRIPTION
**Pull request by allenday**

### CODE REVIEW

**Comment by volsa** [comment]
I've added you as a collaborator, feel free to merge this PR whenever it's ready :)

**Comment by allenday** [comment]
I've operationalized this today 
Screen Shot 2022-11-30 at 23 58 14

**Comment by allenday** [comment]
I don't see that I have merge permissions yet

**Comment by volsa** [comment]
Weird, did you receive a GitHub invite with mail?

**Pull request merged**
